# https://github.com/MatthAmoros/snippets/blob/master/sql/comunas_chile.sql

renovate = [
"""
DROP TABLE IF EXISTS PERMISO_CIRCULACION;
DROP TABLE IF EXISTS PROPIETARIO;
DROP TABLE IF EXISTS VEHICULO;
DROP TABLE IF EXISTS COMUNA;
""",
"""
CREATE TABLE COMUNA (
  ID_Comuna INT AUTO_INCREMENT PRIMARY KEY,
  Nombre_Comuna VARCHAR(64) NOT NULL
);

INSERT INTO COMUNA (Nombre_Comuna)
VALUES
    ("Arica"),
    ("Camarones"),
    ("Putre"),
    ("General Lagos"),
    ("Iquique"),
    ("Alto Hospicio"),
    ("Pozo Almonte"),
    ("Camiña"),
    ("Colchane"),
    ("Huara"),
    ("Pica"),
    ("Antofagasta"),
    ("Mejillones"),
    ("Sierra Gorda"),
    ("Taltal"),
    ("Calama"),
    ("Ollagüe"),
    ("San Pedro de Atacama"),
    ("Tocopilla"),
    ("María Elena"),
    ("Copiapó"),
    ("Caldera"),
    ("Tierra Amarilla"),
    ("Chañaral"),
    ("Diego de Almagro"),
    ("Vallenar"),
    ("Alto del Carmen"),
    ("Freirina"),
    ("Huasco"),
    ("La Serena"),
    ("Coquimbo"),
    ("Andacollo"),
    ("La Higuera"),
    ("Paihuano"),
    ("Vicuña"),
    ("Illapel"),
    ("Canela"),
    ("Los Vilos"),
    ("Salamanca"),
    ("Ovalle"),
    ("Combarbalá"),
    ("Monte Patria"),
    ("Punitaqui"),
    ("Río Hurtado"),
    ("Valparaíso"),
    ("Casablanca"),
    ("Concón"),
    ("Juan Fernández"),
    ("Puchuncaví"),
    ("Quintero"),
    ("Viña del Mar"),
    ("Isla de Pascua"),
    ("Los Andes"),
    ("Calle Larga"),
    ("Rinconada"),
    ("San Esteban"),
    ("La Ligua"),
    ("Cabildo"),
    ("Papudo"),
    ("Petorca"),
    ("Zapallar"),
    ("Quillota"),
    ("La Calera"),
    ("Hijuelas"),
    ("La Cruz"),
    ("Nogales"),
    ("San Antonio"),
    ("Algarrobo"),
    ("Cartagena"),
    ("El Quisco"),
    ("El Tabo"),
    ("Santo Domingo"),
    ("San Felipe"),
    ("Catemu"),
    ("Llay-Llay"),
    ("Panquehue"),
    ("Putaendo"),
    ("Santa María"),
    ("Quilpué"),
    ("Limache"),
    ("Olmué"),
    ("Villa Alemana"),
    ("Rancagua"),
    ("Codegua"),
    ("Coinco"),
    ("Coltauco"),
    ("Doñihue"),
    ("Graneros"),
    ("Las Cabras"),
    ("Machalí"),
    ("Malloa"),
    ("Mostazal"),
    ("Olivar"),
    ("Peumo"),
    ("Pichidegua"),
    ("Quinta de Tilcoco"),
    ("Rengo"),
    ("Requínoa"),
    ("San Vicente"),
    ("Pichilemu"),
    ("La Estrella"),
    ("Litueche"),
    ("Marchihue"),
    ("Navidad"),
    ("Paredones"),
    ("San Fernando"),
    ("Chépica"),
    ("Chimbarongo"),
    ("Lolol"),
    ("Nancagua"),
    ("Palmilla"),
    ("Peralillo"),
    ("Placilla"),
    ("Pumanque"),
    ("Santa Cruz"),
    ("Talca"),
    ("Constitución"),
    ("Curepto"),
    ("Empedrado"),
    ("Maule"),
    ("Pelarco"),
    ("Pencahue"),
    ("Río Claro"),
    ("San Clemente"),
    ("San Rafael"),
    ("Cauquenes"),
    ("Chanco"),
    ("Pelluhue"),
    ("Curicó"),
    ("Hualañé"),
    ("Licantén"),
    ("Molina"),
    ("Rauco"),
    ("Romeral"),
    ("Sagrada Familia"),
    ("Teno"),
    ("Vichuquén"),
    ("Linares"),
    ("Colbún"),
    ("Longaví"),
    ("Parral"),
    ("Retiro"),
    ("San Javier"),
    ("Villa Alegre"),
    ("Yerbas Buenas"),
    ("Chillán"),
    ("Bulnes"),
    ("Chillán Viejo"),
    ("El Carmen"),
    ("Pemuco"),
    ("Pinto"),
    ("Quillón"),
    ("San Ignacio"),
    ("Yungay"),
    ("Quirihue"),
    ("Cobquecura"),
    ("Coelemu"),
    ("Ninhue"),
    ("Portezuelo"),
    ("Ránquil"),
    ("Treguaco"),
    ("San Carlos"),
    ("Coihueco"),
    ("Ñiquén"),
    ("San Fabián"),
    ("San Nicolás"),
    ("Concepción"),
    ("Coronel"),
    ("Chiguayante"),
    ("Florida"),
    ("Hualqui"),
    ("Lota"),
    ("Penco"),
    ("San Pedro de La Paz"),
    ("Santa Juana"),
    ("Talcahuano"),
    ("Tomé"),
    ("Hualpén"),
    ("Lebu"),
    ("Arauco"),
    ("Cañete"),
    ("Contulmo"),
    ("Curanilahue"),
    ("Los Álamos"),
    ("Tirúa"),
    ("Los Ángeles"),
    ("Antuco"),
    ("Cabrero"),
    ("Laja"),
    ("Mulchén"),
    ("Nacimiento"),
    ("Negrete"),
    ("Quilaco"),
    ("Quilleco"),
    ("San Rosendo"),
    ("Santa Bárbara"),
    ("Tucapel"),
    ("Yumbel"),
    ("Alto Biobío"),
    ("Temuco"),
    ("Carahue"),
    ("Cunco"),
    ("Curarrehue"),
    ("Freire"),
    ("Galvarino"),
    ("Gorbea"),
    ("Lautaro"),
    ("Loncoche"),
    ("Melipeuco"),
    ("Nueva Imperial"),
    ("Padre Las Casas"),
    ("Perquenco"),
    ("Pitrufquén"),
    ("Pucón"),
    ("Saavedra"),
    ("Teodoro Schmidt"),
    ("Toltén"),
    ("Vilcún"),
    ("Villarrica"),
    ("Cholchol"),
    ("Angol"),
    ("Collipulli"),
    ("Curacautín"),
    ("Ercilla"),
    ("Lonquimay"),
    ("Los Sauces"),
    ("Lumaco"),
    ("Purén"),
    ("Renaico"),
    ("Traiguén"),
    ("Victoria"),
    ("Valdivia"),
    ("Corral"),
    ("Lanco"),
    ("Los Lagos"),
    ("Máfil"),
    ("Mariquina"),
    ("Paillaco"),
    ("Panguipulli"),
    ("La Unión"),
    ("Futrono"),
    ("Lago Ranco"),
    ("Río Bueno"),
    ("Puerto Montt"),
    ("Calbuco"),
    ("Cochamó"),
    ("Fresia"),
    ("Frutillar"),
    ("Los Muermos"),
    ("Llanquihue"),
    ("Maullín"),
    ("Puerto Varas"),
    ("Castro"),
    ("Ancud"),
    ("Chonchi"),
    ("Curaco de Vélez"),
    ("Dalcahue"),
    ("Puqueldón"),
    ("Queilén"),
    ("Quellón"),
    ("Quemchi"),
    ("Quinchao"),
    ("Osorno"),
    ("Puerto Octay"),
    ("Purranque"),
    ("Puyehue"),
    ("Río Negro"),
    ("San Juan de la Costa"),
    ("San Pablo"),
    ("Chaitén"),
    ("Futaleufú"),
    ("Hualaihué"),
    ("Palena"),
    ("Coyhaique"),
    ("Lago Verde"),
    ("Aysén"),
    ("Cisnes"),
    ("Guaitecas"),
    ("Cochrane"),
    ("O'Higgins"),
    ("Tortel"),
    ("Chile Chico"),
    ("Río Ibáñez"),
    ("Punta Arenas"),
    ("Laguna Blanca"),
    ("Río Verde"),
    ("San Gregorio"),
    ("Cabo de Hornos"),
    ("Antártica"),
    ("Porvenir"),
    ("Primavera"),
    ("Timaukel"),
    ("Natales"),
    ("Torres del Paine"),
    ("Santiago"),
    ("Cerrillos"),
    ("Cerro Navia"),
    ("Conchalí"),
    ("El Bosque"),
    ("Estación Central"),
    ("Huechuraba"),
    ("Independencia"),
    ("La Cisterna"),
    ("La Florida"),
    ("La Granja"),
    ("La Pintana"),
    ("La Reina"),
    ("Las Condes"),
    ("Lo Barnechea"),
    ("Lo Espejo"),
    ("Lo Prado"),
    ("Macul"),
    ("Maipú"),
    ("Ñuñoa"),
    ("Pedro Aguirre Cerda"),
    ("Peñalolén"),
    ("Providencia"),
    ("Pudahuel"),
    ("Quilicura"),
    ("Quinta Normal"),
    ("Recoleta"),
    ("Renca"),
    ("San Joaquín"),
    ("San Miguel"),
    ("San Ramón"),
    ("Vitacura"),
    ("Puente Alto"),
    ("Pirque"),
    ("San José de Maipo"),
    ("Colina"),
    ("Lampa"),
    ("Til Til"),
    ("San Bernardo"),
    ("Buin"),
    ("Calera de Tango"),
    ("Paine"),
    ("Melipilla"),
    ("Alhué"),
    ("Curacaví"),
    ("María Pinto"),
    ("San Pedro"),
    ("Talagante"),
    ("El Monte"),
    ("Isla de Maipo"),
    ("Padre Hurtado"),
    ("Peñaflor")
""",
"""
CREATE TABLE VEHICULO (
    ID_Vehiculo INT AUTO_INCREMENT PRIMARY KEY,
    Año_Fabricacion INT,
    Tipo_Vehiculo VARCHAR(20),
    Marca VARCHAR(20),
    Modelo VARCHAR(50),
    Cilindrada INT,
    Equipamiento VARCHAR(20),
    Combustible VARCHAR(20),
    Transmision VARCHAR(20),
    Tonelaje INT
)
""",
"""
CREATE TABLE PROPIETARIO (
    ID_Propietario INT AUTO_INCREMENT PRIMARY KEY,
    ID_Comuna INT NULL,
    FOREIGN KEY (ID_Comuna) REFERENCES COMUNA(ID_Comuna)
)
""",
"""
CREATE TABLE PERMISO_CIRCULACION (
    ID_Permiso INT AUTO_INCREMENT PRIMARY KEY,
    Fecha_Emision DATE,
    Año INT,
    Tipo_pago VARCHAR(20),
    Cuotas_Permiso VARCHAR(20),
    Codigo_SII VARCHAR(20),
    Valor_Contado INT,
    Total_a_pagar INT,
    Fecha_Vencimiento DATE,
    ID_ComunaAnterior INT,
    ID_Propietario INT,
    ID_ComunaPermiso INT,
    FOREIGN KEY (ID_Propietario) REFERENCES PROPIETARIO(ID_Propietario),
    FOREIGN KEY (ID_ComunaAnterior) REFERENCES COMUNA(ID_Comuna),
    FOREIGN KEY (ID_ComunaPermiso) REFERENCES COMUNA(ID_Comuna)
)
""",
"""
SET SQL_SAFE_UPDATES = 0;
UPDATE `prueba`.`comuna`
SET Nombre_Comuna = UPPER(Nombre_Comuna);

"""
]